 db:
    image: postgres:13-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - '5432:5432'
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data