services:
  app:
    build:
      context: .
      target: development
    command: npm run start:dev
    env_file: 
      - .env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - '5432:5432'
